### ISSUE TITLE
Does this Work?

### ISSUE THREAD

**Issue by SmBro** [vimalcvs/WhatsApp-Stickers-Emoji-App#3]
Whenever i'm giving my admin URL in Config file after building apk it says NO INTERNET CONNECTION.

**Comment by rizwan1239** [comment]
Were you able to figure it out? because I am facing same issue

**Comment by varundeva** [comment]
I hope it may work.
but on Doc they mentioned to enter Envato Purchase Key.
so this project is genune or not?

**Comment by vimalcvs** [comment]
> Whenever I'm giving my admin URL in Config file after building apk it says NO INTERNET CONNECTION.

1. 

>

**Comment by vimalcvs** [comment]
> I hope it may work.
> but on Doc they mentioned to enter Envato Purchase Key.
> so this project is genune or not?

Use this app for educational purposes only.

**Comment by varundeva** [comment]
Is it Nulled Script? Or you built?
Thanks for informing
Else i was planned to prepare build for playstore

**Comment by vimalcvs** [comment]
> Were you able to figure it out? because I am facing same issue

Please update to the new version - [v2.0](https://github.com/vimalcvs/WhatsApp-Stickers-Emoji-App/releases/tag/2.0)

**Comment by vimalcvs** [comment]
> Whenever i'm giving my admin URL in Config file after building apk it says NO INTERNET CONNECTION.

Please update to the new version - [v2.0](https://github.com/vimalcvs/WhatsApp-Stickers-Emoji-App/releases/tag/2.0)
